name: Headwaves Deployment

on:
  push:
    branches:
      - feature/ci-cd-integration

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install npm dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Dependencies
        run: npm i

      - name: Deploy to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws s3 sync --acl public-read ./build/ s3://s3-web-headwaves.dev.bitprism.co

      - name: CloudFront Invalidation
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        run: |
          aws configure set preview.cloudfront true
          aws cloudfront create-invalidation --distribution-id ELKSAG26S63OP --paths "/*"
